name: Build Java App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. Setup Java environment
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Build with Maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # 4. Upload build artefact
      - name: Upload JAR artefact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: target/*.jar
